"""CI schema check

Revision ID: 026935c8bec0
Revises: 41c159645e1b
Create Date: 2025-10-21 13:40:53.699948

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "026935c8bec0"
down_revision: Union[str, Sequence[str], None] = "41c159645e1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
