"""Final, complete schema check

Revision ID: 0bcb4a69aad2
Revises: 20251019_add_sitegen
Create Date: 2025-10-21 16:14:00.123456

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# --- FINAL FIX ---
# Alembic forgot to add this import for your custom EmbeddingType.
import backend

# --- END FINAL FIX ---


# revision identifiers, used by Alembic.
revision: str = "0bcb4a69aad2"
down_revision: Union[str, Sequence[str], None] = "20251019_add_sitegen"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("embedding", backend.models.EmbeddingType(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("assets_pkey")),
    )
    # ... (rest of the autogenerated commands)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ... (rest of the autogenerated commands)
    # ### end Alembic commands ###
