"""Verify everything is in sync

Revision ID: 2887da5e2147
Revises: 0bcb4a69aad2
Create Date: 2025-10-21 12:51:20.536464

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2887da5e2147"
down_revision: Union[str, Sequence[str], None] = "0bcb4a69aad2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("slug", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("site_section")
    op.drop_table("playing_with_neon")
    op.add_column(
        "assets", sa.Column("taste_score", sa.Numeric(precision=3, scale=1), nullable=True)
    )
    op.add_column(
        "assets", sa.Column("emotion_score", sa.Numeric(precision=3, scale=2), nullable=True)
    )
    op.add_column("assets", sa.Column("tone", sa.Text(), nullable=True))
    op.add_column(
        "assets", sa.Column("brand_alignment", sa.Numeric(precision=3, scale=2), nullable=True)
    )
    op.add_column("assets", sa.Column("score", sa.Float(), nullable=True))
    op.add_column("assets", sa.Column("meta", sa.JSON(), nullable=True))
    op.add_column(
        "assets",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "assets",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_assets_id"), "assets", ["id"], unique=False)
    op.alter_column(
        "sitegen_events",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "sitegen_events",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "sitegen_runs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "sitegen_runs",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sitegen_runs",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "sitegen_runs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "sitegen_events",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "sitegen_events",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_assets_id"), table_name="assets")
    op.drop_column("assets", "updated_at")
    op.drop_column("assets", "created_at")
    op.drop_column("assets", "meta")
    op.drop_column("assets", "score")
    op.drop_column("assets", "brand_alignment")
    op.drop_column("assets", "tone")
    op.drop_column("assets", "emotion_score")
    op.drop_column("assets", "taste_score")
    op.create_table(
        "playing_with_neon",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("value", sa.REAL(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="playing_with_neon_pkey"),
    )
    op.create_table(
        "site_section",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("site_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("type", sa.VARCHAR(length=120), autoincrement=False, nullable=False),
        sa.Column("props", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("order", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="site_section_pkey"),
    )
    op.drop_table("site")
    # ### end Alembic commands ###
