"""Final verification

Revision ID: 41c159645e1b
Revises: 2887da5e2147
Create Date: 2025-10-21 13:35:57.178356

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "41c159645e1b"
down_revision: Union[str, Sequence[str], None] = "2887da5e2147"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
