"""Your descriptive message

Revision ID: 8f6f0504e89a
Revises: c4b19650b804
Create Date: 2025-10-21 17:49:30.173606

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f6f0504e89a"
down_revision: Union[str, Sequence[str], None] = "c4b19650b804"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("site_section")
    op.drop_table("page")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "page",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("site_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("path", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("page_pkey")),
    )
    op.create_table(
        "site_section",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("site_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("props", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("order", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("site_section_pkey")),
    )
    # ### end Alembic commands ###
