"""
Test that verifies:
1. Client-facing exports contain NO AICMO/AI branding
2. Exports are properly branded with client name only
"""

import pytest
from pathlib import Path


class TestBrandingLeakRemoval:
    """STEP 6.1: No AICMO/AI branding in client-facing exports."""
    
    def test_export_utils_no_aicmo_branding(self):
        """
        Evidence: backend/export_utils.py:360-365 (REMOVED)
        Expected: No "Generated by AICMO" subtitle
        """
        export_utils = Path(__file__).parent.parent / "backend" / "export_utils.py"
        assert export_utils.exists(), "backend/export_utils.py should exist"
        
        content = export_utils.read_text()
        
        # CRITICAL: Check for the leak we fixed
        assert 'Generated by AICMO' not in content, \
            "BLOCKER: 'Generated by AICMO' found in exports - client embarrassment!"
        assert 'AICMO Report' not in content or 'f"{brief.brand.brand_name}' in content, \
            "Title should use client brand, not 'AICMO Report'"
    
    def test_export_utils_uses_client_brand(self):
        """
        Verify exports use client brand name in title/subtitle.
        """
        export_utils = Path(__file__).parent.parent / "backend" / "export_utils.py"
        content = export_utils.read_text()
        
        # Should reference brief.brand.brand_name (not hardcoded AICMO)
        assert 'brief.brand.brand_name' in content or 'brand_name' in content, \
            "Exports should use client brand_name variable"
    
    def test_no_ai_generated_in_exports(self):
        """
        Check for other AI attribution phrases.
        """
        export_utils = Path(__file__).parent.parent / "backend" / "export_utils.py"
        content = export_utils.read_text()
        
        # Forbidden phrases in export templates
        forbidden = [
            'AI generated',
            'powered by',
            'created by AI',
            'GPT',
            'Claude',
        ]
        
        # This is a heuristic - some mentions might be OK in non-template code
        # But export functions should not include them
        export_functions = content[content.find('def export_'):] if 'def export_' in content else content
        
        for phrase in forbidden:
            count = export_functions.lower().count(phrase.lower())
            # Allow 0 mentions of these phrases in export code
            if count > 0:
                # This might be OK (e.g., in comments), just flag for review
                assert count < 5, \
                    f"Too many '{phrase}' mentions in export code ({count})"


class TestBrandingLeakSearch:
    """STEP 6.2: Comprehensive scan for branding leaks."""
    
    def test_search_for_generated_by_in_codebase(self):
        """
        Scan the entire codebase for "Generated by" which could leak AICMO branding.
        Only allow in comments/docstrings, not in template strings.
        """
        root = Path(__file__).parent.parent
        
        # Run grep to find any mentions
        result = []
        py_files = list(root.glob("backend/**/*.py")) + list(root.glob("aicmo/**/*.py"))
        
        for f in py_files[:20]:  # Check first 20 files (token limit)
            try:
                content = f.read_text()
                if 'Generated by' in content:
                    # Check if it's in a template string (bad) vs comment (OK)
                    lines = content.split('\n')
                    for i, line in enumerate(lines):
                        if 'Generated by' in line:
                            # If it's NOT in a comment, flag it
                            if not line.strip().startswith('#') and not line.strip().startswith('"""'):
                                result.append((f.name, i+1, line.strip()[:80]))
            except:
                pass
        
        assert len(result) == 0, \
            f"Found 'Generated by' in template code (not comments): {result}"


if __name__ == '__main__':
    pytest.main([__file__, '-v'])
