from __future__ import annotations

from alembic import op
import sqlalchemy as sa

"""Revision script generated by alembic."""

revision = "d629c4a0a1b7"
down_revision = "20251019_pgvector_guard"
branch_labels = None
depends_on = None


def upgrade():
    """Write your upgrade migrations here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("assets", sa.Column("score", sa.Float(), nullable=True))
    op.add_column("assets", sa.Column("meta", sa.JSON(), nullable=True))
    op.add_column(
        "assets",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "assets",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "assets", "name", existing_type=sa.TEXT(), type_=sa.String(length=255), nullable=True
    )
    op.drop_index("idx_assets_brand", table_name="assets")
    op.drop_index(
        "idx_assets_embedding_ivf",
        table_name="assets",
        postgresql_with={"lists": "100"},
        postgresql_using="ivfflat",
    )
    op.drop_index("idx_assets_taste", table_name="assets")
    op.create_index(op.f("ix_assets_id"), "assets", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    """Write your downgrade migrations here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_assets_id"), table_name="assets")
    op.create_index("idx_assets_taste", "assets", ["taste_score"], unique=False)
    op.create_index(
        "idx_assets_embedding_ivf",
        "assets",
        ["embedding"],
        unique=False,
        postgresql_with={"lists": "100"},
        postgresql_using="ivfflat",
    )
    op.create_index("idx_assets_brand", "assets", ["brand_alignment"], unique=False)
    op.alter_column(
        "assets", "name", existing_type=sa.String(length=255), type_=sa.TEXT(), nullable=False
    )
    op.drop_column("assets", "updated_at")
    op.drop_column("assets", "created_at")
    op.drop_column("assets", "meta")
    op.drop_column("assets", "score")
    op.drop_table("site")
    # ### end Alembic commands ###
