#!/bin/bash
# AICMO QUICK START GUIDE
#
# This script provides immediate next steps to launch AICMO in production

echo ""
echo "================================================================================"
echo "                    AICMO ACTIVATION QUICK START"
echo "================================================================================"
echo ""
echo "✅ ALL SYSTEMS GO - AICMO is ready for operation"
echo ""
echo "VERIFIED COMPONENTS:"
echo "  1. ✅ DB Schema (5 AOL tables created)"
echo "  2. ✅ Canonical UI (streamlit_pages/aicmo_operator.py)"
echo "  3. ✅ LLM Handling (gracefully disabled without key)"
echo "  4. ✅ Public APIs (clean imports)"
echo "  5. ✅ Daemon Loop (runs 2+ ticks)"
echo "  6. ✅ Autonomy Tab (DB-backed monitoring)"
echo "  7. ✅ PROOF POST_SOCIAL (end-to-end)"
echo ""
echo "================================================================================"
echo "                          LAUNCH OPTIONS"
echo "================================================================================"
echo ""
echo "Option 1: Start Daemon (PROOF mode - no real external calls)"
echo "  $ python scripts/run_aol_daemon.py --proof"
echo "  $ python scripts/run_aol_daemon.py --proof --ticks 10  # Run 10 ticks then exit"
echo ""
echo "Option 2: Launch Operator UI (Streamlit Dashboard)"
echo "  $ streamlit run streamlit_pages/aicmo_operator.py"
echo "  $ streamlit run streamlit_pages/aicmo_operator.py --server.port 8501"
echo ""
echo "Option 3: Use Launcher Script"
echo "  $ bash scripts/launch_operator_ui.sh"
echo "  $ bash scripts/launch_operator_ui.sh --server.port 8501"
echo ""
echo "================================================================================"
echo "                          TESTING"
echo "================================================================================"
echo ""
echo "Run all AOL tests (17 test cases):"
echo "  $ pytest tests/orchestration/test_aol.py -v"
echo ""
echo "Run with coverage:"
echo "  $ pytest tests/orchestration/test_aol.py -v --cov=aicmo.orchestration"
echo ""
echo "================================================================================"
echo "                     DEVELOPMENT REFERENCES"
echo "================================================================================"
echo ""
echo "AOL Package Structure:"
echo "  aicmo/orchestration/"
echo "  ├── models.py             (5 DB tables: control_flags, tick_ledger, lease, actions, execution_logs)"
echo "  ├── daemon.py             (main loop, lease management, tick execution)"
echo "  ├── queue.py              (action enqueue/dequeue/retry/DLQ logic)"
echo "  ├── lease.py              (distributed lock for daemon exclusivity)"
echo "  └── adapters/"
echo "      └── social_adapter.py (POST_SOCIAL action handler for PROOF/REAL modes)"
echo ""
echo "Database URL Configuration:"
echo "  Default: sqlite:////local.db"
echo "  Override: DATABASE_URL=postgresql://... python scripts/run_aol_daemon.py --proof"
echo ""
echo "================================================================================"
echo "                        CONTROL FLAGS (UI BUTTONS)"
echo "================================================================================"
echo ""
echo "In Operator UI → Autonomy tab, you can:"
echo "  • Pause/Resume Daemon (pauses action processing)"
echo "  • Clear DLQ (marks dead letters as CANCELLED)"
echo "  • Kill Daemon (daemon exits on next tick)"
echo ""
echo "================================================================================"
echo "                        PROOF vs REAL MODES"
echo "================================================================================"
echo ""
echo "PROOF Mode (Default for activation):"
echo "  • All actions write artifacts only (no real execution)"
echo "  • Artifacts stored in /tmp/artifacts/proof_social/"
echo "  • SHA256 hashing included for integrity"
echo "  • Database writes included"
echo "  • Enabled via: --proof flag or AOL_PROOF_MODE env var"
echo ""
echo "REAL Mode:"
echo "  • Raises REAL_RUN_UNCONFIGURED by default"
echo "  • Prevents accidental production execution"
echo "  • Must explicitly configure real integrations"
echo "  • Execution logs include FAILED status with block reason"
echo ""
echo "================================================================================"
echo "                      QUICK REFERENCE: KEY FILES"
echo "================================================================================"
echo ""
echo "Daemon:"
echo "  • Runner: scripts/run_aol_daemon.py"
echo "  • Logic: aicmo/orchestration/daemon.py"
echo "  • Usage: python scripts/run_aol_daemon.py --proof --ticks 5"
echo ""
echo "UI:"
echo "  • Canonical: streamlit_pages/aicmo_operator.py"
echo "  • Launcher: scripts/launch_operator_ui.sh"
echo "  • Tab: _render_autonomy_tab() function (line ~936)"
echo ""
echo "Tests:"
echo "  • Location: tests/orchestration/test_aol.py"
echo "  • Count: 17 test cases"
echo "  • Status: All passing"
echo ""
echo "================================================================================"
echo ""
echo "For full documentation, see AOL_DEPLOYMENT_GUIDE.md"
echo ""
